VERSION 1.0 CLASS
BEGIN
  MultiUse = -1 
END
Attribute VB_Name = "mySplitBrand"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
Option Explicit

Public strName as String
Public strCountSalons as Integer
Public strCountHaircareSalons as Integer
Public strCountSkincareSalons as Integer
Public strCountNailSalons as Integer
Public strCountColoxSalons as Integer

