VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "Person"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
Option Explicit

Public CountStreet As Integer
Public StreetGeo As String

Public CountCity As Integer
Public CityGeo As String

Public RegionGeo As String
Public CountRegion As Integer

Public SectorCom As String
Public CountSector As Integer

