VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  
END
Attribute VB_Name = "UserEducated"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False

Option Explicit

Public cdDateStat As Date
Public PersonName As String
Public Role As String
Public Status As String
Public Mobile As String
Public Mail As String
Public Partner As String
Public Experience As String
Public Territory As String
Public ParentTerritory As String
Public Brand_LP As String
Public Brand_MX As String
Public Brand_KR As String
Public Brand_RD As String
Public Brand_ES As String
Public Brand_DE As String
Public Brand_CR As String
Public Brand_Other As String
Public TeamType As String
Public MegaReg As String
Public EduDate As Date
Public diffEduDate As Integer
Public Educater As String
Public EducatedStatus As String
Public Seminar1 As String
Public Seminar2 As String
Public Seminar3 As String
Public Seminar4 As String
Public Seminar5 As String
Public Seminar6 As String
Public Seminar7 As String
Public Seminar8 As String
Public Seminar9 As String
Public Seminar10 As String
Public Seminar11 As String
Public Seminar12 As String
Public Seminar13 As String
Public Seminar14 As String
Public Seminar15 As String
Public Seminar16 As String
Public Seminar17 As String
Public Seminar18 As String
Public Seminar19 As String
Public Seminar20 As String

