VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  
END
Attribute VB_Name = "UserData"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False

Option Explicit

Public cdDateStat As Date
Public PersonName As String
Public Role As String
Public Status As String
Public Mobile As String
Public Mail As String
Public Partner As String
Public Experience As String
Public Territory As String
Public ParentTerritory As String
Public Brand_LP As String
Public Brand_MX As String
Public Brand_KR As String
Public Brand_RD As String
Public Brand_ES As String
Public Brand_DE As String
Public Brand_CR As String
Public MegaReg As String

